export { FullWidthProfileTopCard } from './TopCard'
export { FullWidthProfileMain } from './Main'
export { FullWidthProfilePanel } from './Panel'
export { FullWidthProfileHeaderBackground } from './HeaderBackground'
export { FullWidthProfileHeaderBackgroundWide } from './HeaderBackgroundWide'
export { FullWidthProfileRole } from './Role'
export { FullWidthProfileMoreOptions } from './MoreOptions'
export { FullWidthProfileStatusSection } from './StatusSection'
export { FullWidthProfileContent } from './Content'
export { FullWidthProfileAvatar } from './Avatar'
export { FullWidthProfileDetails } from './Details'
export { FullWidthProfileName } from './Name'
export { FullWidthProfileStats } from './Stats'
export { FullWidthProfileStatusMobile } from './StatusMobile'
export { FullWidthProfileBio } from './Bio'
export { FullWidthProfileSocials } from './Socials'
export { FullWidthProfileCommonFollowers } from './CommonFollowers'

export type { FullWidthProfileSlotProps } from './slot.types'
